# Generated by Django 3.1.2 on 2023-06-22 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0003_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
