# Generated by Django 3.1.2 on 2023-06-22 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0004_delete_contacto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contacto',
        ),
    ]
