# Generated by Django 3.1.2 on 2023-06-23 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0005_auto_20230621_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
