# Generated by Django 3.1.2 on 2023-07-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0007_carrito_carritoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
