# Generated by Django 3.1.2 on 2023-07-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0008_auto_20230705_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='MontoExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
            ],
        ),
    ]
