# Generated by Django 3.1.2 on 2023-07-09 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0010_compra_perfilusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='user',
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
