# Generated by Django 3.1.2 on 2023-07-09 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0012_auto_20230709_1754'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compra',
        ),
    ]
